### ISSUE TITLE
HomeScreen 감정우표, BottomSheetDialog 일기카드 기능 구현

### ISSUE THREAD

**Issue by tristanjung1006** [Team-ToYou/ToYou-Android#13]
## Issue

이슈 내용: HomeScreen 감정우표, BottomSheetDialog 일기카드 기능 구현

## Branch Name

 생성 브랜치 이름 : feature/home

## To-Do List

- [x] 감정 선택에 따른 인스턴트 화면 띄우기
- [x] 감정에 따른 홈화면 배경 변경
- [x] BottomSheetDialog 스크롤뷰 + 리사이클러뷰 조합
- [x] 알림창 UI
- [x] 감정우표 선택 화면 UI
- [x] 홈화면 UI

https://github.com/user-attachments/assets/b3c1d503-548c-4d41-b124-54dd5d3ff942

https://github.com/user-attachments/assets/89414a42-f3da-4313-a175-63d5992c1fca
