### ISSUE TITLE
일기카드 달력 기능 구현

### ISSUE THREAD

**Issue by tristanjung1006** [Team-ToYou/ToYou-Android#14]
## Issue

이슈 내용: 일기카드 달력 기능 구현

## To-Do List

- [x] 나, 친구 기록 TabLayout으로 분리
- [x] 요일, 날짜 분리해서 RecyclerView로 구성
- [x] 오늘 날짜 돌아가기 기능
- [x] 캘린더 무한 ViewPager2
- [x] 날짜 클릭시 기록탭 날짜 변경
- [x] 나의 기록 날짜별 감정우표 표시
- [x] 친구 기록 날짜별 친구 감정우표 개수 표시

## Video
https://github.com/user-attachments/assets/8311b71b-83a6-4862-8eb6-d13b8e7df418

## Etc
나의 기록과 친구 기록에서 쓰이는 Adapter를 재활용하지 않고 분리함
- 재활용할 경우 코드 중복이 줄어들고 유지보수할 때 편함
- 나의 기록에는 날짜에 감정우표가 표시되는 기능만 존재하고 친구 기록에는 추가 기능이 더 붙기 때문에 유지보수가 용이하다는 명분이 부족함
- TabLayout으로 Fragment를 교체, 생성하는 방식이고 서버와 실시간으로 통신하여 정보를 받아오기 때문에 재활용보다는 초기 화면 생성 때 분리시킴으로써 지연시간을 조금이라도 줄일 수 있음
