### ISSUE TITLE
2차 QA 피드백

### ISSUE THREAD

**Issue by tristanjung1006** [Team-ToYou/ToYou-Android#30]
## To-Do List

- [x] 초기화면 로고 위치 조정
- [x] 회원가입 제목 줄간격 조정
- [x] 회원가입 버튼 색상 더 밝게
- [x] 회원가입 체크박스 크기 조정
- [x] 회원가입 버튼 위치 및 폰트 크기 조정
- [x] 닉네임 글자수 카운팅, 입력칸, 중복확인 정렬
- [x] 닉네임 글자 공백 -> 중복확인 비활성화, 공백 X -> 활성화
- [x] 닉네임 글자입력칸 배경색 조정 bg -> white
- [x] 일기카드 0개일 경우 바텀시트 화면 추가
- [x] 홈화면 불안감정 날짜배경색 수정
- [x] 홈화면 날짜 라벨과 숫자 수직 정렬
- [x] 감정우표 선택화면 부제목 폰트 변경
- [x] 감정우표 결과화면 애니메이션 지속시간 단축 4초 -> 2초
- [x] 알림메시지 친구수락 버튼 패딩값으로 설정 및 음영 제거
- [x] 알림메시지 슬라이드시 휴지통 아이콘 삭제옵션 추가
- [x] 알림메시지 가로 길이 고정값이 아닌 패딩값 부여
- [x] 마이페이지 프로필은 기본값으로 유지
- [x] 마이페이지 뒤로 가기 버튼 제거 및 제목 위치 조정
- [x] 마이페이지 로그아웃, 회원탈퇴 모달창
- [x] 마이페이지 프로필 닉네임 수정 기능 추가
- [x] 회원탈퇴, 로그아웃 버튼 음영 제거
- [x] 캘린더 기록 탭 하단선 추가, 폰트 조정
- [x] 캘린더 화면 전체 스크롤로 변경
- [x] 친구기록 레이아웃 아이콘 5개까지만 표시
- [x] 친구기록 닉네임 글자가 길어지면 온점(...) 처리
- [x] 뒤로가기 버튼 클릭 영역 확장, 위치 아래로 조정

## ScreenShot
<p align="center">
<a href="link"><img src="https://github.com/user-attachments/assets/f793b0dc-9a9f-464b-8cde-c737704f3c10" align="center" width="30%"></a>
<a href="link"><img src="https://github.com/user-attachments/assets/238f907b-0c6a-4177-9948-9a7979591c1c" align="center" width="30%"></a>
<a href="link"><img src="https://github.com/user-attachments/assets/79aee7a2-779b-4057-ba09-bafe0fced674" align="center" width="30%"></a>
</p>
<p align="center">
<a href="link"><img src="https://github.com/user-attachments/assets/b3905112-cc06-4231-9f81-3fc0f9788191" align="center" width="30%"></a>
<a href="link"><img src="https://github.com/user-attachments/assets/eb1c0aa1-a6e2-462c-b7cf-8cecd10f90ec" align="center" width="30%"></a>
<a href="link"><img src="https://github.com/user-attachments/assets/3313bdeb-4881-4cda-954d-2b5b5780563f" align="center" width="30%"></a>
</p>
