### ISSUE TITLE
API 연결

### ISSUE THREAD

**Issue by tristanjung1006** [Team-ToYou/ToYou-Android#35]
## To-Do List

- [x] 로그인
- [x] 회원가입, 탈퇴, 로그아웃
- [x] 닉네임 수정
- [x] 닉네임 중복확인
- [ ] 홈화면 일기카드
- [x] 캘린더 나의 기록
- [x] 캘린더 친구 기록
- [x] 마이페이지
- [x] 알림 조회
- [x] 알림 삭제
