### ISSUE TITLE
세부 이슈

### ISSUE THREAD

**Issue by jeong724** [Team-ToYou/ToYou-Android#38]
## Issue

이슈 내용: 작업 마무리 단계에서 필요한 작업들

## Branch Name

 생성 브랜치 이름 : `feature/social`

## To-Do List

- [x] 확인 버튼 비활성화 .. 답변 미 입력시
- [ ] 스택 삭제
- [x] 검색할때 api 콜백 받고 창 없애기
- [x] fcm 토큰 적용
- [x] 감정 선택 안했을때 카드 생성 불가능 토스트
- [x] fcm 전송 로직(토큰, 닉네임 잘 넣어주기)
- [x] 카드 프리뷰에서 색깔 설정
- [x] 카드 수정 잘되는지 확인
- [x] 글자 입력 제한
- [x] 친구 요청에서 스스로 요청하는 경우와 닉네임이 존재하지 않는 경우 케이스도 작업 필요
- [x] 홈화면 조회 api -> 수정 api 로직
