### ISSUE TITLE
Big Issue 점검

### ISSUE THREAD

**Issue by tristanjung1006** [Team-ToYou/ToYou-Android#58]
## To-Do List

- [x] 회원탈퇴 버튼 클릭 안됨 + 프론트에서 초기화 처리 필요
- [x] 뒤로가기, 닫기 버튼 클릭 반경 넓히기
- [x] 백스택 관리 필요 (ex. 일기카드 생성 > 질문 선택에서 선택하지 않고 나갔을때 감정 애니메이션 뜸)
- [ ] 바텀 시트 구현 마무리
- [x] 감정우표 선택  버그
- [x] 일기카드 삭제 구현하기 + 모달창 잘 뜨는지 확인
- [x] 나의 기록 > 일기카드 확대 > 공개/비공개(자물쇠) 구현
- [x] 마이페이지 > 현재상태만 변경해도 다음 버튼 활성화시키기
- [x] 로그인 토큰 만료 문제
