### ISSUE TITLE
Final Issue

### ISSUE THREAD

**Issue by jeong724** [Team-ToYou/ToYou-Android#60]
## Issue

이슈 내용: 빅이슈 (기능) + 디자인 QA 수정 사항 반영

but,, 빅이슈는 완료되서 디자인 QA만 반영하면 될것같습니다!

## Branch Name

 생성 브랜치 이름 : `release/hyunjeong`

## To-Do List

- [ ] 일기카드 > 질문 선택 & 답변 입력 텍스트 깨짐(텍스트 줄바꿈 기준 한번 더 확인 필요) 
- [x] 일기카드 선택형 질문 색상 강조 버그
- [x] fcm 토큰 갱신 api 연동
- [x] fcm topic 구독
- [x] fcm 토큰 로컬에 잘 저장되는지 확인
