### ISSUE TITLE
[FIX] 선택형 질문 깨짐

### ISSUE THREAD

**Issue by jeong724** [Team-ToYou/ToYou-Android#75]
## Issue

이슈 내용: 선택형 질문 깨짐 + 다음 버튼 색 변화 안됨

## Branch Name

 생성 브랜치 이름 : `release/#75`

## To-Do List

- [x] 선택형 질문 글자수 제한 추가
- [ ] 카드에서 깨지는거 테스트
- [x] 다음 버튼 색 변화 주기
