### ISSUE TITLE
베타테스트 최종점검

### ISSUE THREAD

**Issue by tristanjung1006** [Team-ToYou/ToYou-Android#83]
## Branch Name

 생성 브랜치 이름 : `refactor/#83`

## To-Do List

- [x] 친구 수락 API 호출 점검
- [x] 튜토리얼 이미지 해상도
- [x] 모달창 크기 통일
